# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.3
  - 1.4
os:
  - linux
  - osx
  - windows
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build();' 
  - julia -e 'Pkg.add("Coverage"); using Coverage;'
  - travis_wait 50 julia -e 'Pkg.test( ; coverage=true)'

# jobs:
#   fast_finish: true
#   # allow_failures:
#   #   - julia: 1.3
after_success:
  - julia -e 'Codecov.submit(process_folder())'