# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.3
  - 1.4
os:
  - linux
  - osx
  - windows

notifications:
  email: false

arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
script:
  - while sleep 30; do echo "still alive"; done &
  - julia -e 'using Pkg; Pkg.test("MSQR");'
jobs:
  fast_finish: true
  # allow_failures:
  #   - julia: 1.3
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'