# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.3
  - 1.4
os:
  - linux
  - windows
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
env:
  - TEST_SUITE=integration_tests
  - TEST_SUITE=unit_tests
script: bundle exec rake test:$TEST_SUITE
  - while sleep 30; do echo "still alive"; done &
  - julia -e 'using Pkg; Pkg.test("MSQR");'
jobs:
  include:
    - stage: deploy
      env: TEST_SUITE=none
      install: skip # bundle install is not required
      script: ./deploy.sh
  fast_finish: true
  # allow_failures:
  #   - julia: 1.3
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'