# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.3
  - 1.4
os:
  - linux
  - osx
  - windows
arch:
  - x64
env:
  - JULIA_NUM_THREADS=2
cache:
  directories:
    - ~/.julia/artifacts
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes --check-bounds=yes -e 'import Pkg; Pkg.instantiate(); Pkg.build();'
  - travis_wait 48 julia --project --color=yes --check-bounds=yes -e 'import Pkg; Pkg.test( ; coverage=true)';

jobs:
  fast_finish: true

after_success:
  - |
  - julia -e '
      import Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'